// Mock data for demo mode
import type { User, Project, Site, Borehole, WaterLevel, PumpTest, WaterQuality, ProjectDashboard } from '@/types';

export const mockUser: User = {
  id: 'demo-user-1',
  email: 'demo@aquapack.io',
  name: 'Demo User',
  role: 'DATA_MANAGER',
  organizationId: 'demo-org-1',
  isActive: true,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-15T00:00:00Z',
};

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Kano State Groundwater Assessment',
    code: 'KN-GW-2024',
    client: 'Kano State Ministry of Water Resources',
    region: 'Kano, Nigeria',
    description: 'Comprehensive groundwater assessment covering 15 LGAs in Kano State',
    startDate: '2024-01-10',
    endDate: '2024-12-31',
    organizationId: 'demo-org-1',
    isActive: true,
    templateConfig: {
      clientContact: 'Dr. Aminu Yusuf',
      clientEmail: 'aminu.yusuf@kanostate.gov.ng',
      clientPhone: '+234 803 456 7890',
      country: 'NG',
      defaultUnits: { depth: 'meters', discharge: 'l/s' },
      coordinateSystem: 'WGS84',
      gpsAccuracyThreshold: 5,
      enabledModules: ['boreholes', 'waterLevels', 'pumpTests', 'waterQuality', 'media'],
    },
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
    _count: { sites: 45 },
  },
  {
    id: 'proj-2',
    name: 'Niger Delta Aquifer Study',
    code: 'ND-AQ-2024',
    client: 'Federal Ministry of Environment',
    region: 'Rivers State, Nigeria',
    description: 'Deep aquifer characterization in the Niger Delta region',
    startDate: '2024-02-01',
    endDate: '2025-06-30',
    organizationId: 'demo-org-1',
    isActive: true,
    templateConfig: {
      clientContact: 'Engr. Blessing Okafor',
      clientEmail: 'b.okafor@fme.gov.ng',
      clientPhone: '+234 805 123 4567',
      country: 'NG',
      defaultUnits: { depth: 'meters', discharge: 'm3/h' },
      coordinateSystem: 'WGS84',
      gpsAccuracyThreshold: 10,
      enabledModules: ['boreholes', 'waterLevels', 'pumpTests', 'waterQuality'],
    },
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
    _count: { sites: 28 },
  },
  {
    id: 'proj-3',
    name: 'Abuja FCT Water Supply',
    code: 'ABJ-WS-2024',
    client: 'FCT Water Board',
    region: 'Abuja FCT, Nigeria',
    description: 'Borehole siting and development for FCT water supply expansion',
    startDate: '2024-02-20',
    endDate: '2024-08-31',
    organizationId: 'demo-org-1',
    isActive: true,
    templateConfig: {
      clientContact: 'Mr. James Adewale',
      clientEmail: 'j.adewale@fctwaterboard.gov.ng',
      clientPhone: '+234 809 876 5432',
      country: 'NG',
      defaultUnits: { depth: 'meters', discharge: 'l/s' },
      coordinateSystem: 'WGS84',
      gpsAccuracyThreshold: 8,
      enabledModules: ['boreholes', 'waterLevels', 'pumpTests', 'media'],
    },
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
    _count: { sites: 12 },
  },
  {
    id: 'proj-4',
    name: 'Kaduna Rural Water Project',
    code: 'KD-RW-2023',
    client: 'UNICEF Nigeria',
    region: 'Kaduna State, Nigeria',
    description: 'Rural water supply boreholes for underserved communities',
    startDate: '2023-06-01',
    endDate: '2023-12-15',
    organizationId: 'demo-org-1',
    isActive: false,
    templateConfig: {
      clientContact: 'Sarah Johnson',
      clientEmail: 's.johnson@unicef.org',
      clientPhone: '+234 812 345 6789',
      country: 'NG',
      defaultUnits: { depth: 'meters', discharge: 'l/s' },
      coordinateSystem: 'WGS84',
      gpsAccuracyThreshold: 15,
      enabledModules: ['boreholes', 'waterLevels', 'waterQuality', 'media'],
    },
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2023-12-15T00:00:00Z',
    _count: { sites: 67 },
  },
];

export const mockSites: Site[] = [
  {
    id: 'site-1',
    projectId: 'proj-1',
    name: 'Nassarawa GRA Borehole',
    code: 'KN-NAS-001',
    latitude: 12.0022,
    longitude: 8.5167,
    accuracy: 3.5,
    altitude: 472,
    description: 'Main production well for Nassarawa Government Residential Area',
    siteType: 'PRODUCTION',
    accessNotes: 'Gate access requires prior notification',
    qaStatus: 'APPROVED',
    syncStatus: 'SYNCED',
    createdBy: 'demo-user-1',
    createdAt: '2024-01-15T08:30:00Z',
    updatedAt: '2024-01-20T14:00:00Z',
    project: { id: 'proj-1', name: 'Kano State Groundwater Assessment', code: 'KN-GW-2024' },
    creator: { id: 'demo-user-1', name: 'Demo User' },
    _count: { boreholes: 2, waterLevels: 15, pumpTests: 3, waterQualityReadings: 8 },
  },
  {
    id: 'site-2',
    projectId: 'proj-1',
    name: 'Sabon Gari Market Well',
    code: 'KN-SBG-002',
    latitude: 11.9872,
    longitude: 8.5342,
    accuracy: 2.8,
    altitude: 465,
    description: 'Community well serving Sabon Gari market area',
    siteType: 'COMMUNITY',
    accessNotes: 'Best access via main market road',
    qaStatus: 'PENDING',
    syncStatus: 'SYNCED',
    createdBy: 'demo-user-1',
    createdAt: '2024-01-18T10:15:00Z',
    updatedAt: '2024-01-18T10:15:00Z',
    project: { id: 'proj-1', name: 'Kano State Groundwater Assessment', code: 'KN-GW-2024' },
    creator: { id: 'demo-user-1', name: 'Demo User' },
    _count: { boreholes: 1, waterLevels: 8, pumpTests: 1, waterQualityReadings: 4 },
  },
  {
    id: 'site-3',
    projectId: 'proj-1',
    name: 'Gwale LGA Monitoring Well',
    code: 'KN-GWL-003',
    latitude: 11.9654,
    longitude: 8.4987,
    accuracy: 4.2,
    altitude: 458,
    description: 'Long-term monitoring piezometer',
    siteType: 'MONITORING',
    qaStatus: 'FLAGGED',
    syncStatus: 'SYNCED',
    createdBy: 'demo-user-1',
    createdAt: '2024-01-20T14:30:00Z',
    updatedAt: '2024-01-25T09:00:00Z',
    project: { id: 'proj-1', name: 'Kano State Groundwater Assessment', code: 'KN-GW-2024' },
    creator: { id: 'demo-user-1', name: 'Demo User' },
    _count: { boreholes: 1, waterLevels: 22, pumpTests: 0, waterQualityReadings: 2 },
  },
  {
    id: 'site-4',
    projectId: 'proj-2',
    name: 'Port Harcourt Industrial BH',
    code: 'ND-PH-001',
    latitude: 4.8156,
    longitude: 7.0498,
    accuracy: 2.1,
    altitude: 18,
    description: 'Deep borehole for industrial estate',
    siteType: 'PRODUCTION',
    qaStatus: 'APPROVED',
    syncStatus: 'SYNCED',
    createdBy: 'demo-user-1',
    createdAt: '2024-02-05T11:00:00Z',
    updatedAt: '2024-02-10T16:30:00Z',
    project: { id: 'proj-2', name: 'Niger Delta Aquifer Study', code: 'ND-AQ-2024' },
    creator: { id: 'demo-user-1', name: 'Demo User' },
    _count: { boreholes: 1, waterLevels: 10, pumpTests: 2, waterQualityReadings: 6 },
  },
  {
    id: 'site-5',
    projectId: 'proj-3',
    name: 'Maitama District Well',
    code: 'ABJ-MT-001',
    latitude: 9.0876,
    longitude: 7.4967,
    accuracy: 1.8,
    altitude: 512,
    description: 'High-yield production well for Maitama district',
    siteType: 'PRODUCTION',
    qaStatus: 'PENDING',
    syncStatus: 'PENDING',
    createdBy: 'demo-user-1',
    createdAt: '2024-02-25T09:45:00Z',
    updatedAt: '2024-02-25T09:45:00Z',
    project: { id: 'proj-3', name: 'Abuja FCT Water Supply', code: 'ABJ-WS-2024' },
    creator: { id: 'demo-user-1', name: 'Demo User' },
    _count: { boreholes: 1, waterLevels: 5, pumpTests: 1, waterQualityReadings: 3 },
  },
];

export const mockBoreholes: Borehole[] = [
  {
    id: 'bh-1',
    siteId: 'site-1',
    name: 'Main Production Well',
    wellType: 'PRODUCTION',
    totalDepth: 120,
    depthUnit: 'METERS',
    drillingDate: '2024-01-12',
    drillingMethod: 'ROTARY_MUD',
    driller: 'National Water Drilling Ltd',
    diameter: 200,
    staticWaterLevel: 15.5,
    notes: 'Excellent yield, high quality aquifer',
    qaStatus: 'APPROVED',
    boreholeStatus: 'OPERATIONAL',
    _count: { waterLevels: 10, pumpTests: 2, waterQualityReadings: 5 },
  },
  {
    id: 'bh-2',
    siteId: 'site-1',
    name: 'Observation Well OW-1',
    wellType: 'OBSERVATION',
    totalDepth: 80,
    depthUnit: 'METERS',
    drillingDate: '2024-01-14',
    drillingMethod: 'ROTARY_AIR',
    driller: 'National Water Drilling Ltd',
    diameter: 100,
    staticWaterLevel: 14.8,
    qaStatus: 'APPROVED',
    boreholeStatus: 'COMPLETED',
    _count: { waterLevels: 5, pumpTests: 1, waterQualityReadings: 3 },
  },
  {
    id: 'bh-3',
    siteId: 'site-2',
    name: 'Community Hand Pump',
    wellType: 'HAND_PUMP',
    totalDepth: 45,
    depthUnit: 'METERS',
    drillingDate: '2023-08-20',
    drillingMethod: 'CABLE_TOOL',
    diameter: 150,
    staticWaterLevel: 8.2,
    qaStatus: 'PENDING',
    boreholeStatus: 'DRILLING',
    _count: { waterLevels: 8, pumpTests: 1, waterQualityReadings: 4 },
  },
  {
    id: 'bh-4',
    siteId: 'site-3',
    name: 'Industrial Deep Well',
    wellType: 'PRODUCTION',
    totalDepth: 180,
    depthUnit: 'METERS',
    drillingDate: '2024-02-01',
    drillingMethod: 'ROTARY_MUD',
    driller: 'Premier Drilling Co',
    diameter: 250,
    staticWaterLevel: 25.3,
    qaStatus: 'APPROVED',
    boreholeStatus: 'COMPLETED',
    _count: { waterLevels: 12, pumpTests: 3, waterQualityReadings: 6 },
  },
  {
    id: 'bh-5',
    siteId: 'site-4',
    name: 'School Borehole',
    wellType: 'HAND_PUMP',
    totalDepth: 55,
    depthUnit: 'METERS',
    drillingDate: '2023-11-15',
    drillingMethod: 'ROTARY_AIR',
    diameter: 150,
    staticWaterLevel: 12.1,
    qaStatus: 'APPROVED',
    boreholeStatus: 'OPERATIONAL',
    _count: { waterLevels: 6, pumpTests: 1, waterQualityReadings: 3 },
  },
  {
    id: 'bh-6',
    siteId: 'site-5',
    name: 'Failed Well - Dry',
    wellType: 'PRODUCTION',
    totalDepth: 90,
    depthUnit: 'METERS',
    drillingDate: '2023-09-10',
    drillingMethod: 'ROTARY_MUD',
    driller: 'National Water Drilling Ltd',
    diameter: 200,
    notes: 'Dry hole - abandoned at 90m',
    qaStatus: 'REJECTED',
    boreholeStatus: 'ABANDONED',
    _count: { waterLevels: 0, pumpTests: 0, waterQualityReadings: 0 },
  },
  {
    id: 'bh-7',
    siteId: 'site-5',
    name: 'Replacement Well',
    wellType: 'PRODUCTION',
    totalDepth: 110,
    depthUnit: 'METERS',
    drillingDate: '2024-01-25',
    drillingMethod: 'ROTARY_MUD',
    driller: 'National Water Drilling Ltd',
    diameter: 200,
    staticWaterLevel: 18.5,
    qaStatus: 'PENDING',
    boreholeStatus: 'DRILLING',
    _count: { waterLevels: 3, pumpTests: 0, waterQualityReadings: 1 },
  },
  {
    id: 'bh-8',
    siteId: 'site-1',
    name: 'Test Well TW-1',
    wellType: 'TEST',
    totalDepth: 60,
    depthUnit: 'METERS',
    drillingDate: '2024-02-10',
    drillingMethod: 'ROTARY_AIR',
    diameter: 100,
    staticWaterLevel: 16.2,
    qaStatus: 'PENDING',
    boreholeStatus: 'DRILLING',
    _count: { waterLevels: 2, pumpTests: 1, waterQualityReadings: 0 },
  },
];

export const mockWaterLevels: WaterLevel[] = [
  {
    id: 'wl-1',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    measurementDatetime: '2024-01-20T08:00:00Z',
    depthToWater: 15.45,
    depthUnit: 'METERS',
    measurementMethod: 'ELECTRIC_TAPE',
    measurementType: 'STATIC',
    referencePoint: 'TOP_OF_CASING',
    notes: 'Clear morning measurement',
    qaStatus: 'APPROVED',
  },
  {
    id: 'wl-2',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    measurementDatetime: '2024-01-21T08:00:00Z',
    depthToWater: 15.52,
    depthUnit: 'METERS',
    measurementMethod: 'ELECTRIC_TAPE',
    measurementType: 'STATIC',
    referencePoint: 'TOP_OF_CASING',
    qaStatus: 'APPROVED',
  },
  {
    id: 'wl-3',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    measurementDatetime: '2024-01-22T08:00:00Z',
    depthToWater: 15.38,
    depthUnit: 'METERS',
    measurementMethod: 'ELECTRIC_TAPE',
    measurementType: 'STATIC',
    referencePoint: 'TOP_OF_CASING',
    qaStatus: 'PENDING',
  },
];

export const mockPumpTests: PumpTest[] = [
  {
    id: 'pt-1',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    testType: 'CONSTANT_RATE',
    testName: 'Initial Yield Test',
    startDatetime: '2024-01-15T09:00:00Z',
    endDatetime: '2024-01-15T17:00:00Z',
    staticWaterLevel: 15.5,
    pumpDepth: 60,
    pumpType: 'SUBMERSIBLE',
    notes: '8-hour constant rate test at 10 L/s',
    qaStatus: 'APPROVED',
  },
  {
    id: 'pt-2',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    testType: 'STEP_DRAWDOWN',
    testName: 'Step Test',
    startDatetime: '2024-01-16T08:00:00Z',
    endDatetime: '2024-01-16T14:00:00Z',
    staticWaterLevel: 15.6,
    pumpDepth: 60,
    pumpType: 'SUBMERSIBLE',
    notes: '6-hour step test with 4 steps',
    qaStatus: 'APPROVED',
  },
];

export const mockWaterQuality: WaterQuality[] = [
  {
    id: 'wq-1',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    sampleDatetime: '2024-01-15T10:30:00Z',
    sampleId: 'KN-NAS-001-WQ-001',
    temperature: 28.5,
    ph: 7.2,
    electricalConductivity: 485,
    totalDissolvedSolids: 312,
    dissolvedOxygen: 6.8,
    turbidity: 1.2,
    notes: 'Sample taken during pump test',
    qaStatus: 'APPROVED',
  },
  {
    id: 'wq-2',
    siteId: 'site-1',
    boreholeId: 'bh-1',
    sampleDatetime: '2024-01-20T14:00:00Z',
    sampleId: 'KN-NAS-001-WQ-002',
    temperature: 29.1,
    ph: 7.1,
    electricalConductivity: 492,
    totalDissolvedSolids: 318,
    dissolvedOxygen: 6.5,
    turbidity: 0.8,
    qaStatus: 'PENDING',
  },
];

export const mockDashboard: ProjectDashboard = {
  projectId: 'proj-1',
  sitesTotal: 45,
  sitesCompleted: 32,
  boreholesTotal: 52,
  waterLevelCount: 245,
  pumpTestCount: 38,
  waterQualityCount: 89,
  pendingReviewCount: 12,
  flaggedCount: 3,
};

// Demo credentials
export const DEMO_CREDENTIALS = {
  email: 'demo@aquapack.io',
  password: 'demo123',
};
